riscv: page: cast arguments of copy_page() to uintptr_t*
Casting the arguments provides a hint to the compiler that the
arguments of copy_page() and copy_user_page() are always at least
alignof(uintptr_t) aligned (actually, they are required to be even
strong aligned to page boundaries).

Providing this alignment information avoids cheri-inefficient
disagnostics being emitted by CHERI LLVM 19. For example, when
compiling using CHERI LLVM 19 the following is emitted:

mm/hugetlb_vmemmap.c:252:2: error: memmove operation with capability argument  and underaligned destination (aligned to 1 bytes) may be inefficient or result in CHERI tags bits being stripped [-Werror,-Wcheri-inefficient]
252 |         memcpy(start, from, sizeof(*from) * NR_RESET_STRUCT_PAGE);
    |         ^

Even though this message points to the memcpy() used by
reset_struct_pages() and about the destination being underaligned, it is
actually about the source argument of copy_page() invoked in
vmemmap_restore_pte().

Here, the compiler is unable to show that reuse_addr has a higher
alignment than 1, resulting in the cheri-inefficient diagnostic for
the memmove() operation behind copy_page(). This patch gets rid of the
cheri-inefficient diagnostic by providing the compiler with
information about sufficient alignment.

Signed-off-by: Florian Schmaus <florian.schmaus@codasip.com>