net: tun: Fix ioctl handler argument type
With the introduction of capabilities, the PCuABI expects a
capability when dealing with the user pointers.

When the TUN driver is enabled in a PCuABI compatible kernel,
the compiler reports the error below:

drivers/net/tun.c:3502:20: error: incompatible function pointer types
initializing 'long (*)(struct file *, unsigned int, user_uintptr_t)'
(aka 'long (*)(struct file *, unsigned int, unsigned __intcap)')
with an expression of type 'long (struct file *, unsigned int,
unsigned long)' [-Werror,-Wincompatible-function-pointer-types]
        .unlocked_ioctl = tun_chr_ioctl,
                          ^~~~~~~~~~~~~
1 error generated.

Address the issue using the proper type to represent user
pointers (user_uintptr_t). Also make sure to always create a valid
user pointer in tun_chr_compat_ioctl() by using compat_ptr(); this
was only done for a small and very incomplete list of requests that
expect a pointer.

Tested-by: David Horton <david.horton@cyberhive.com>
Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
Co-developed-by: Kevin Brodsky <kevin.brodsky@arm.com>
Signed-off-by: Kevin Brodsky <kevin.brodsky@arm.com>