tracing: Fix signature of unlocked_ioctl callback
Commit 01b2a5217173 ("tracing: Add ioctl() to force ring buffer waiters
to wake up") added a callback to unlocked_ioctl, however in PCuABI the
function signature of file_operations->unlocked_ioctl in
include/linux/fs.h has been changed to take a user_uintptr_t arg as the
third param.

Update the signature of tracing_buffers_ioctl to avoid compilation
errors as below when tracing is enabled.

kernel/trace/trace.c:8396:20: error: incompatible function pointer types
initializing 'long (*)(struct file *, unsigned int, user_uintptr_t)'
(aka 'long (*)(struct file *, unsigned int, unsigned __intcap)') with an
expression of type 'long (struct file *, unsigned int, unsigned long)'
[-Werror,-Wincompatible-function-pointer-types]

Reported-by: Teo Couprie Diaz <teo.coupriediaz@arm.com>
Signed-off-by: Zachary Leaf <zachary.leaf@arm.com>