net: Fix the position of __capability in double pointer
With the introduction of capabilities, the PCuABI expects a
capability when dealing with the user pointers.

Address the compilation issues below triggered by otherwise
implicit conversion that might lead to unexpected behaviour when
operating on capabilities.

make[1]: linux/net/bridge/br_ioctl.c:
error: use of __capability is ambiguous
        void __user **argp, void __user *data)

Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>